### ISSUE TITLE
Events' replies

### ISSUE THREAD

**Issue by vSLG** [mirukana/mio#18]
Currently, there are no reply helpers in mio, you cannot easily reply to an event, and neither extract `m.in_reply_to` from event content. Some ideas:

- [x] Get event reply information (in event's content, `m.relates_to -> m.in_reply_to`)
- [x] `Text`/`Notice` event helper for creating a reply (e.g. `Text.replies_to(event: TimelineEvent)`)
- [x] `Text`/`Notice` event helper/attribute body text without reply body

**Comment by mirukana** [comment]
Added in #19
